* Development
** References
*** [[http://net.tutsplus.com/tutorials/tools-and-tips/how-to-work-with-github-and-multiple-accounts/][using github with multiple accounts]]

    So you have a personal GitHub account; everything is working perfectly. But then, you get a new job, and now need
    to have the ability to push and pull to multiple accounts. How do you do that? I’ll show you how!

*** [[http://daringfireball.net/projects/markdown/syntax][Markdown: Syntax]]

    Markdown is intended to be as easy-to-read and easy-to-write as is feasible.

    Readability, however, is emphasized above all else. A Markdown-formatted document should be publishable as-is, as
    plain text, without looking like it’s been marked up with tags or formatting instructions. While Markdown’s syntax
    has been influenced by several existing text-to-HTML filters — including Setext, atx, Textile, reStructuredText,
    Grutatext, and EtText — the single biggest source of inspiration for Markdown’s syntax is the format of plain text
    email.

